存档修改 - 龙红

diff --git a/docker-compose/local/docker-compose.yml b/docker-compose/local/docker-compose.yml
--- a/docker-compose/local/docker-compose.yml
+++ b/docker-compose/local/docker-compose.yml
@@ -1,4 +1,4 @@
-name: lobe-chat-database
+name: longhong-chat-database
 services:
   network-service:
     image: alpine
@@ -8,10 +8,10 @@ services:
       - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
       - '9001:9001' # MinIO Console
       - '${CASDOOR_PORT}:${CASDOOR_PORT}' # Casdoor
-      - '${LOBE_PORT}:3210' # LobeChat
+      - '${LOBE_PORT}:3210' # 龙红
     command: tail -f /dev/null
     networks:
-      - lobe-network
+      - longhong-network
 
   postgresql:
     image: pgvector/pgvector:pg17
@@ -59,24 +59,24 @@ services:
       "
 
 # version lock ref: https://github.com/lobehub/lobe-chat/pull/7331
-  casdoor:
-    image: casbin/casdoor:v1.843.0
-    container_name: lobe-casdoor
-    entrypoint: /bin/sh -c './server --createDatabase=true'
-    network_mode: 'service:network-service'
-    depends_on:
-      postgresql:
-        condition: service_healthy
-    environment:
-      httpport: ${CASDOOR_PORT}
-      RUNNING_IN_DOCKER: 'true'
-      driverName: 'postgres'
-      dataSourceName: 'user=postgres password=${POSTGRES_PASSWORD} host=postgresql port=5432 sslmode=disable dbname=casdoor'
-      runmode: 'dev'
-    volumes:
-      - ./init_data.json:/init_data.json
-    env_file:
-      - .env
+#   casdoor:
+#     image: casbin/casdoor:v1.843.0
+#     container_name: lobe-casdoor
+#     entrypoint: /bin/sh -c './server --createDatabase=true'
+#     network_mode: 'service:network-service'
+#     depends_on:
+#       postgresql:
+#         condition: service_healthy
+#     environment:
+#       httpport: ${CASDOOR_PORT}
+#       RUNNING_IN_DOCKER: 'true'
+#       driverName: 'postgres'
+#       dataSourceName: 'user=postgres password=${POSTGRES_PASSWORD} host=postgresql port=5432 sslmode=disable dbname=casdoor'
+#       runmode: 'dev'
+#     volumes:
+#       - ./init_data.json:/init_data.json
+#     env_file:
+#       - .env
 
   searxng:
     image: searxng/searxng
@@ -87,13 +87,13 @@ services:
       - 'SEARXNG_SETTINGS_FILE=/etc/searxng/settings.yml'
     restart: always
     networks:
-      - lobe-network
+      - longhong-network
     env_file:
       - .env
 
   lobe:
-    image: lobehub/lobe-chat-database
-    container_name: lobe-chat
+    image: longhong-tech/longhong-chat-database
+    container_name: longhong-chat
     network_mode: 'service:network-service'
     depends_on:
       postgresql:
@@ -102,13 +102,14 @@ services:
         condition: service_started
       minio:
         condition: service_started
-      casdoor:
-        condition: service_started
+      # casdoor:
+      #   condition: service_started
 
     environment:
-      - 'NEXT_AUTH_SSO_PROVIDERS=casdoor'
-      - 'KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ='
-      - 'NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg'
+      # - 'NEXT_AUTH_SSO_PROVIDERS=casdoor'
+      # - 'KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ='
+      # - 'NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg'
+      - 'NEXT_PUBLIC_ENABLE_NEXT_AUTH=0'
       - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
       - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
       - 'S3_ENABLE_PATH_STYLE=1'
@@ -126,29 +127,29 @@ services:
         /bin/node /app/startServer.js &
         LOBE_PID=\$!
         sleep 3
-        if [ $(wget --timeout=5 --spider --server-response ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -c 'HTTP/1.1 200 OK') -eq 0 ]; then
-          echo '⚠️Warining: Unable to fetch OIDC configuration from Casdoor'
-          echo 'Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
-          echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
-          echo ''
-          echo '⚠️注意：无法从 Casdoor 获取 OIDC 配置'
-          echo '请求 URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
-          echo '了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration'
-          echo ''
-        else
-          if ! wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep 'issuer' | grep ${AUTH_CASDOOR_ISSUER}; then
-            printf '❌Error: The Auth issuer is conflict, Issuer in OIDC configuration is: %s' \$(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E 'issuer.*' | awk -F '\"' '{print \$4}')
-            echo ' , but the issuer in .env file is: ${AUTH_CASDOOR_ISSUER} '
-            echo 'Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
-            echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
-            echo ''
-            printf '❌错误：Auth 的 issuer 冲突，OIDC 配置中的 issuer 是：%s' \$(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E 'issuer.*' | awk -F '\"' '{print \$4}')
-            echo ' , 但 .env 文件中的 issuer 是：${AUTH_CASDOOR_ISSUER} '
-            echo '请求 URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
-            echo '了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration'
-            echo ''
-          fi
-        fi
+        # if [ $(wget --timeout=5 --spider --server-response ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -c 'HTTP/1.1 200 OK') -eq 0 ]; then
+        #   echo '⚠️Warining: Unable to fetch OIDC configuration from Casdoor'
+        #   echo 'Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
+        #   echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+        #   echo ''
+        #   echo '⚠️注意：无法从 Casdoor 获取 OIDC 配置'
+        #   echo '请求 URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
+        #   echo '了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+        #   echo ''
+        # else
+        #   if ! wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep 'issuer' | grep ${AUTH_CASDOOR_ISSUER}; then
+        #     printf '❌Error: The Auth issuer is conflict, Issuer in OIDC configuration is: %s' \$(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E 'issuer.*' | awk -F '\"' '{print \$4}')
+        #     echo ' , but the issuer in .env file is: ${AUTH_CASDOOR_ISSUER} '
+        #     echo 'Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
+        #     echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+        #     echo ''
+        #     printf '❌错误：Auth 的 issuer 冲突，OIDC 配置中的 issuer 是：%s' \$(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E 'issuer.*' | awk -F '\"' '{print \$4}')
+        #     echo ' , 但 .env 文件中的 issuer 是：${AUTH_CASDOOR_ISSUER} '
+        #     echo '请求 URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
+        #     echo '了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+        #     echo ''
+        #   fi
+        # fi
         if [ $(wget --timeout=5 --spider --server-response ${S3_ENDPOINT}/minio/health/live 2>&1 | grep -c 'HTTP/1.1 200 OK') -eq 0 ]; then
           echo '⚠️Warining: Unable to fetch MinIO health status'
           echo 'Request URL: ${S3_ENDPOINT}/minio/health/live'
@@ -169,5 +170,5 @@ volumes:
     driver: local
 
 networks:
-  lobe-network:
+  longhong-network:
     driver: bridge
